   name: Publsh thymeleaf dialect library to GitHub Packages

    on:
      push:
        branches: [ master ]
    
    jobs:
      pulish:
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-java@v1
            with:
              java-version: 17
    
          # Runs a set of commands using the runners shell
          - name: Publish library
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run:
              gradle publish
